#!/bin/env bash
This scrip displays
to infinity and beyond indefinitely 
with a sleep 2 in between each iteration
I am invicible!!! when receiving aa SIGTERM signal

trap 'echo' "I am invicible!!!"' 15
while true; do
	echo "to infinity and beyond"
	sleep 2
done
