#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes:
#   display hours from 0 to 12
#   display minutes from 1 to 59

HOUR=0

while [ "$HOUR" -lt 13 ]; do
  echo "Hour: $HOUR"
  MINUTES=1
  while [ "$MINUTES" -lt 60 ]; do
    echo "$MINUTES"
    ((MINUTES++))
  done
  ((HOUR++))
done
